version: "3.9"
services:
  postgres:
    container_name: postgres
    image: "postgres:13.2"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./data/database/sql:/docker-entrypoint-initdb.d/:ro
    environment:
      - POSTGRES_USER="dev"
      - POSTGRES_PASSWORD="pwd"
      - PGADMIN_DEFAULT_EMAIL="user@domain.local"
      - PGADMIN_DEFAULT_PASSWORD="admin"
    ports:
      - "5432:5432"
    networks:
      - backend
  pgadmin:
    container_name: pgadmin
    image: "dpage/pgadmin4:5.1"
    environment:
      - POSTGRES_USER="dev"
      - POSTGRES_PASSWORD="pwd"
      - PGADMIN_DEFAULT_EMAIL="user@domain.local"
      - PGADMIN_DEFAULT_PASSWORD="admin"
    ports:
      - "5050:80"
    networks: 
      - backend
  keycloak:
    container_name: keycloak
    image: "jboss/keycloak:16.1.1"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DEBUG=true
      - DEBUG_PORT='*:8787'
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=kc
      - TZ=Europe/Paris
    depends_on:
      - "postgres"
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
